//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/uah_asw_iface_v1.h>
#include <public/cctcmanager_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
extern "C" rtems_task Init (uint32_t arg){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
	UAH_ASW	comp1(1, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp1Memory());
	CCTCManager	comp2(2, 10, EDROOMprioHigh, 4096, systemDeployment.GetComp2Memory());
 
	systemDeployment.Config(&comp1, &comp2);
 
	systemDeployment.Start();
 
	;
 
}
