//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/systemmng_iface_v1.h>
#include <public/displaysmng_iface_v1.h>
#include <public/ledmng_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
rtems_task Init (uint32_t arg){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
	SystemMng	comp2(2, 11, EDROOMprioNormal, 1024, systemDeployment.GetComp2Memory());
	DisplaysMng	comp3(3, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp3Memory());
	LEDMng	comp4(4, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp4Memory());
 
	systemDeployment.Config(&comp2, &comp3, &comp4);
 
	systemDeployment.Start();
 
	;
 
}
